[package]
name = "gelly"
version = "1.16.0"
edition = "2024"

[dependencies]
gtk = { version = "0.11.5", package = "gtk4", features = ["v4_22"] }
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_9"] }
log = { version = "0.4.34", features = ["std"] }
env_logger = { version = "0.11.11", features = ["color"] }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "sync", "fs"] }
reqwest = { version = "0.13.5", features = ["json", "query"] }
serde_json = { version = "1.0.151", features = ["std"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.21"
gstreamer = { version = "0.25.4", features = ["v1_26"] }
gstreamer-pbutils = { version = "0.25.4", features = ["v1_26"] }
async-channel = "2.5.0"
futures-util = "0.3.34"
mpris-server = "0.10.0"
glycin = { version = "4.0.2", features = ["gdk4"] }
futures = "0.3.34"
uuid = { version = "1.27.0", features = ["v4"] }
rand = "0.10.3"
md5 = "0.8.1"
num_enum = "0.7.6"
lru = "0.18.5"
gettext-rs = { version = "0.8.0", features = ["gettext-system"] }
oo7 = { version = "0.6.0", default-features = false, features = ["async-std", "native_crypto"] }
async-io = "2.6.0"
diacritics = "0.2.2"

[build-dependencies]
glib-build-tools = "0.22.8"
